--------------------------------------------------------
--  File created - Monday-September-10-2018   
--------------------------------------------------------
@D:\Projects\Final\SRMS\database\DROP.sql
@D:\Projects\Final\SRMS\database\BOOKING.sql
@D:\Projects\Final\SRMS\database\FEATURE.sql
@D:\Projects\Final\SRMS\database\INVITATION.sql
@D:\Projects\Final\SRMS\database\LOCATION.sql
@D:\Projects\Final\SRMS\database\LOCATIONRESOURCE.sql
@D:\Projects\Final\SRMS\database\RESOURCEFEATURE.sql
@D:\Projects\Final\SRMS\database\RESOURCES.sql
@D:\Projects\Final\SRMS\database\RESOURCETYPE.sql
@D:\Projects\Final\SRMS\database\USERS.sql
@D:\Projects\Final\SRMS\database\VISITOR.sql
@D:\Projects\Final\SRMS\database\BOOKING_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\FEATURE_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\INVITATION_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\LOCATION_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\LOCATIONRESOURCE_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\RESOURCEFEATURE_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\RESOURCES_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\RESOURCETYPE_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\USERS_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\VISITOR_DATA_TABLE.sql
@D:\Projects\Final\SRMS\database\SYS_C007203.sql
@D:\Projects\Final\SRMS\database\SYS_C007182.sql
@D:\Projects\Final\SRMS\database\SYS_C007183.sql
@D:\Projects\Final\SRMS\database\SYS_C007207.sql
@D:\Projects\Final\SRMS\database\SYS_C007171.sql
@D:\Projects\Final\SRMS\database\SYS_C007180.sql
@D:\Projects\Final\SRMS\database\SYS_C007186.sql
@D:\Projects\Final\SRMS\database\SYS_C007175.sql
@D:\Projects\Final\SRMS\database\SYS_C007172.sql
@D:\Projects\Final\SRMS\database\SYS_C007173.sql
@D:\Projects\Final\SRMS\database\SYS_C007191.sql
@D:\Projects\Final\SRMS\database\SYS_C007196.sql
@D:\Projects\Final\SRMS\database\SYS_C007197.sql
@D:\Projects\Final\SRMS\database\BOOKING_CONSTRAINT.sql
@D:\Projects\Final\SRMS\database\FEATURE_CONSTRAINT.sql
@D:\Projects\Final\SRMS\database\INVITATION_CONSTRAINT.sql
@D:\Projects\Final\SRMS\database\LOCATION_CONSTRAINT.sql
@D:\Projects\Final\SRMS\database\LOCATIONRESOURCE_CONSTRAINT.sql
@D:\Projects\Final\SRMS\database\RESOURCEFEATURE_CONSTRAINT.sql
@D:\Projects\Final\SRMS\database\RESOURCES_CONSTRAINT.sql
@D:\Projects\Final\SRMS\database\RESOURCETYPE_CONSTRAINT.sql
@D:\Projects\Final\SRMS\database\USERS_CONSTRAINT.sql
@D:\Projects\Final\SRMS\database\VISITOR_CONSTRAINT.sql
