--------------------------------------------------------
--  Constraints for Table INVITATION
--------------------------------------------------------

  ALTER TABLE "PRMSADMIN"."INVITATION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PRMSADMIN"."INVITATION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PRMSADMIN"."INVITATION" ADD PRIMARY KEY ("INVID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRMSTABLESPACE"  ENABLE;
