--------------------------------------------------------
--  DDL for Table INVITATION
--------------------------------------------------------

  CREATE TABLE "PRMSADMIN"."INVITATION" 
   (	"INVID" NUMBER(*,0), 
	"USERID" NUMBER(*,0), 
	"BOOKINGID" NUMBER(*,0), 
	"STATUS" VARCHAR2(10 BYTE), 
	"VISID" NUMBER(*,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRMSTABLESPACE" ;
