--------------------------------------------------------
--  Constraints for Table RESOURCES
--------------------------------------------------------

  ALTER TABLE "PRMSADMIN"."RESOURCES" MODIFY ("ROOMNUMBER" NOT NULL ENABLE);
  ALTER TABLE "PRMSADMIN"."RESOURCES" MODIFY ("RESNAME" NOT NULL ENABLE);
  ALTER TABLE "PRMSADMIN"."RESOURCES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PRMSADMIN"."RESOURCES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PRMSADMIN"."RESOURCES" ADD PRIMARY KEY ("RESID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRMSTABLESPACE"  ENABLE;
