REM INSERTING into PRMSADMIN.RESOURCETYPE
SET DEFINE OFF;
Insert into PRMSADMIN.RESOURCETYPE (RETID,RETNAME,RETICONNAME,DESCRIPTION) values (1,'Scrum','scrum.png','Dont know');
Insert into PRMSADMIN.RESOURCETYPE (RETID,RETNAME,RETICONNAME,DESCRIPTION) values (2,'Board','board.png','DK');
Insert into PRMSADMIN.RESOURCETYPE (RETID,RETNAME,RETICONNAME,DESCRIPTION) values (3,'Class','class.png','dk');
Insert into PRMSADMIN.RESOURCETYPE (RETID,RETNAME,RETICONNAME,DESCRIPTION) values (4,'Rec','rec.png','dk');
Insert into PRMSADMIN.RESOURCETYPE (RETID,RETNAME,RETICONNAME,DESCRIPTION) values (5,'break','rec2.png','dk');
Insert into PRMSADMIN.RESOURCETYPE (RETID,RETNAME,RETICONNAME,DESCRIPTION) values (6,'Lounge','rec3.png','dk');
Insert into PRMSADMIN.RESOURCETYPE (RETID,RETNAME,RETICONNAME,DESCRIPTION) values (7,'Conference','conf.png','dk');
