--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PRMSADMIN"."USERS" 
   (	"USERID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"USEREMAIL" VARCHAR2(255 BYTE), 
	"USERPASSWORD" VARCHAR2(255 BYTE), 
	"USERTYPE" VARCHAR2(20 BYTE), 
	"USERPHONE" VARCHAR2(15 BYTE), 
	"LOCID" NUMBER(*,0), 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRMSTABLESPACE" ;
