REM INSERTING into PRMSADMIN.VISITOR
SET DEFINE OFF;
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (1,'Abdullah Ross','befriendpoison@gmail.com','(398)373-6576',4529246,'Do not know','JPMorgan Chase');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (2,'Elliott Bryant','moyairelease@gmail.com','(542)342-7598',4404635,'Do not know','General Motors');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (3,'Mario Sanchez','welshsemiotics@gmail.com','(920)202-3937',5856375,'Do not know','BNP Paribas');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (4,'Asa Bennett','stilttalking@gmail.com','(884)124-3073',3691166,'Do not know','Sinopec');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (5,'Reginald White','handlingcanape@gmail.com','(427)147-3714',3596133,'Do not know','Chevron');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (6,'Alejandro Gray','martingalenuptse@gmail.com','(342)482-9662',1349770,'Do not know','BNP Paribas');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (7,'Michael Baker','pensiveinvolved@gmail.com','(788)623-1210',4009614,'Do not know','Toyota');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (8,'Dean Brown','ticketmixing@gmail.com','(821)737-7928',8487303,'Do not know','Samsung');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (9,'Lennox Sanchez','dyesmig@gmail.com','(858)609-9641',4317041,'Do not know','Honda');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (10,'Callum Simmons','guffawmutable@gmail.com','(566)163-1912',7023529,'Do not know','ATT');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (11,'Joseph Hall','rossprimary@gmail.com','(517)559-9616',4690932,'Do not know','Japan Post Holdings');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (12,'Vaughn Brown','graftfuture@gmail.com','(513)672-1834',1700081,'Do not know','AXA');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (13,'Anders Torres','screenshotdatabase@gmail.com','(471)868-6397',7079345,'Do not know','Ping An Insurance');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (14,'Sonny Morris','mitralantelope@gmail.com','(932)780-2547',3132177,'Do not know','Volkswagen');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (15,'Briar Jackson','firstmoors@gmail.com','(838)341-1452',8222287,'Do not know','Industrial  Commercial Bank of China');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (16,'Alexzander Lewis','distantoval@gmail.com','(266)645-1927',5429033,'Do not know','Japan Post Holdings');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (17,'Izaiah Clark','presentingdigit@gmail.com','(960)377-153',6355458,'Do not know','Volkswagen');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (18,'Odin Lewis','coodignore@gmail.com','(651)818-4445',714344,'Do not know','Walgreens Boots Alliance');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (19,'Jon Price','toxinadmire@gmail.com','(855)835-3993',3100740,'Do not know','China State Construction');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (20,'Barrett Bell','chondrulevanish@gmail.com','(553)919-2638',4914531,'Do not know','Exxon Mobil');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (21,'Albert Flores','geminisob@gmail.com','(551)868-3315',2846827,'Do not know','Chevron');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (22,'Rhys Perry','optimismskirting@gmail.com','(866)813-9517',1332695,'Do not know','Exor');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (23,'Maddux Coleman','optimismskirting@gmail.com','(256)527-7982',6538070,'Do not know','Kroger');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (24,'Davis Gonzalez','cuttingsense@gmail.com','(853)991-6476',9663413,'Do not know','CVS Health');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (25,'Brixton Thompson','nestinggrapnel@gmail.com','(318)134-4301',6491148,'Do not know','Verizon');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (26,'Rylan Brown','crestedbisque@gmail.com','(665)808-7408',9650056,'Do not know','General Electric');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (27,'Leighton Smith','referredbimming@gmail.com','(798)451-347',8419945,'Do not know','State Grid');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (28,'Francis Perez','spoonerrant@gmail.com','(716)282-5758',330310,'Do not know','Cardinal Health');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (29,'Mateo White','pencilpolicy@gmail.com','(754)153-4848',298373,'Do not know','Agricultural Bank of China');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (30,'Gabriel Adams','quantuisotope@gmail.com','(927)947-8018',7574081,'Do not know','General Motors');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (31,'Joaquin Washington','mustercharter@gmail.com','(602)871-139',3799842,'Do not know','ATT');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (32,'Markus Wood','breaksled@gmail.com','(935)681-5014',6894258,'Do not know','Daimler');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (33,'Jett Diaz','referredbimming@gmail.com','(672)194-708',7039694,'Do not know','AmerisourceBergen');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (34,'Malakai Butler','strumpethunt@gmail.com','(223)740-488',8359906,'Do not know','Trafigura');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (35,'Landon Perez','moyairelease@gmail.com','(853)387-1063',2636872,'Do not know','Ford');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (36,'Yusuf Brooks','abclongterm@gmail.com','(880)476-325',3981716,'Do not know','Daimler');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (37,'Johnathan Gray','landlustard@gmail.com','(982)565-5370',2081341,'Do not know','Allianz');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (38,'Diego Evans','quantuisotope@gmail.com','(714)358-5277',2710396,'Do not know','Exxon Mobil');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (39,'Trent Walker','coodignore@gmail.com','(409)426-1268',6106811,'Do not know','China National Petroleum');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (40,'Gerald Lee','abclongterm@gmail.com','(238)218-2621',2994531,'Do not know','Ford');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (41,'Ariel Lee','jappinesssproiled@gmail.com','(732)169-9091',5646745,'Do not know','Royal Dutch Shell');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (42,'Kaleb Brown','froggeryfaithless@gmail.com','(518)962-2568',6158980,'Do not know','General Motors');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (43,'Kenny Harris','befriendpoison@gmail.com','(622)919-5396',5119048,'Do not know','Ford');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (44,'Jonas Hughes','adjustscales@gmail.com','(589)917-3413',1850093,'Do not know','Ping An Insurance');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (45,'Bryant Collins','frapkink@gmail.com','(774)576-5021',886640,'Do not know','China Life Insurance');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (46,'Judson Coleman','leukocyteseems@gmail.com','(925)919-1374',7541339,'Do not know','Costco');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (47,'Noe Morgan','belchedsignaler@gmail.com','(631)755-7031',4892454,'Do not know','Total');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (48,'Landyn Walker','pencilpolicy@gmail.com','(329)418-2892',9983194,'Do not know','General Motors');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (49,'Christian Scott','yoodynaive@gmail.com','(709)884-2236',5758559,'Do not know','Fannie Mae');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (50,'Samir Coleman','parpgraphic@gmail.com','(717)491-3750',9900051,'Do not know','Fannie Mae');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (51,'Colin Green','yahooantenna@gmail.com','(575)137-6223',5538854,'Do not know','Chevron');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (52,'Achilles Ramirez','hourgannet@gmail.com','(475)801-9678',6668743,'Do not know','Bank of China');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (53,'Major Russell','gotthem@gmail.com','(772)654-1141',7268859,'Do not know','Honda');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (54,'Eden Turner','zestyski@gmail.com','(336)288-5295',5955133,'Do not know','Walgreens Boots Alliance');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (55,'Louie Perez','hivepassage@gmail.com','(961)177-896',8671131,'Do not know','Foxconn');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (56,'Austin King','chirmcity@gmail.com','(586)772-8696',8536583,'Do not know','Trafigura');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (57,'Jameson Foster','boeingcastar@gmail.com','(658)408-1947',1341994,'Do not know','AXA');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (58,'Tate Scott','asprinredirect@gmail.com','(532)978-1150',6306158,'Do not know','State Grid');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (59,'Jax Brooks','martingalenuptse@gmail.com','(407)932-2047',4231611,'Do not know','JPMorgan Chase');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (60,'Ezra Johnson','irritatingsulky@gmail.com','(733)398-4283',6097690,'Do not know','China Life Insurance');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (61,'Rhys Green','portatoblutting@gmail.com','(692)280-6026',5066754,'Do not know','Walgreens Boots Alliance');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (62,'Paul Smith','crowdedvergence@gmail.com','(461)842-6967',6488163,'Do not know','Chevron');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (63,'Pierce Thomas','roofingtrench@gmail.com','(834)972-1978',848043,'Do not know','Chevron');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (64,'Nicholas Perez','dressguttural@gmail.com','(790)920-6253',592501,'Do not know','Toyota');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (65,'Garrett Phillips','welshsemiotics@gmail.com','(831)443-557',8423533,'Do not know','Cardinal Health');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (66,'Romeo Robinson','abclongterm@gmail.com','(576)903-924',6460396,'Do not know','Total');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (67,'Hudson Barnes','halegeneral@gmail.com','(965)593-8905',4146198,'Do not know','McKesson');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (68,'Dallas Rivera','horseswooth@gmail.com','(460)701-6773',4115609,'Do not know','Daimler');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (69,'Alonso Jenkins','dressguttural@gmail.com','(559)542-7261',8449771,'Do not know','JPMorgan Chase');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (70,'Donovan Parker','masculinerice@gmail.com','(245)239-4055',2414076,'Do not know','Foxconn');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (71,'Kairo Young','paddlingverbena@gmail.com','(713)830-7973',8020969,'Do not know','Walgreens Boots Alliance');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (72,'Mateo Harris','kerneltrunks@gmail.com','(784)883-4225',4653814,'Do not know','CVS Health');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (73,'Kendall Perez','healdipstick@gmail.com','(675)944-5019',1708231,'Do not know','Total');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (74,'Nikolas Wilson','guffawmutable@gmail.com','(934)700-3280',6376551,'Do not know','Berkshire Hathaway');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (75,'William Harris','gyrusbasement@gmail.com','(702)822-2191',1853726,'Do not know','SAIC Motor');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (76,'Jasper Williams','pensiveinvolved@gmail.com','(534)525-3826',7032852,'Do not know','Cardinal Health');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (77,'Matteo Ramirez','teamkayaking@gmail.com','(630)160-4294',636242,'Do not know','Apple');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (78,'Thomas Ramirez','chellscreamy@gmail.com','(815)855-153',7917353,'Do not know','Kroger');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (79,'Cameron Baker','inningboundless@gmail.com','(550)183-9645',4465203,'Do not know','Chevron');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (80,'Huxley Evans','belchedsignaler@gmail.com','(461)721-7958',5614636,'Do not know','Honda');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (81,'Chad Torres','intendedreach@gmail.com','(713)801-1230',5785139,'Do not know','McKesson');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (82,'Chris Hughes','jellyfishskillful@gmail.com','(985)987-9443',4458101,'Do not know','McKesson');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (83,'Travis Bennett','inningboundless@gmail.com','(822)639-1620',795379,'Do not know','Exor');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (84,'Damian Lewis','nestinggrapnel@gmail.com','(534)515-3676',6583271,'Do not know','SAIC Motor');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (85,'Cesar Moore','usagepolenta@gmail.com','(989)661-3475',3406776,'Do not know','AmerisourceBergen');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (86,'Nathan Martin','gyrusbasement@gmail.com','(566)556-9584',421159,'Do not know','BNP Paribas');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (87,'Zachary Garcia','crowdedvergence@gmail.com','(626)771-5419',5218101,'Do not know','Foxconn');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (88,'Maverick Bailey','ironicbumpkin@gmail.com','(580)655-5547',1541318,'Do not know','Kroger');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (89,'Hudson Jones','teamkayaking@gmail.com','(465)156-6666',9102967,'Do not know','Allianz');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (90,'Lawrence Gray','strumpethunt@gmail.com','(232)469-3814',2415202,'Do not know','AXA');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (91,'Kamden Russell','wocksaxel@gmail.com','(776)271-8967',8413113,'Do not know','Cardinal Health');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (92,'Leland Kelly','welshsemiotics@gmail.com','(830)421-4949',4714205,'Do not know','China Life Insurance');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (93,'Tatum Cook','graniticdrouse@gmail.com','(214)487-600',656007,'Do not know','Total');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (94,'Thaddeus Reed','jappinesssproiled@gmail.com','(257)344-8283',1423430,'Do not know','Daimler');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (95,'Finley Simmons','sharkeyes@gmail.com','(964)783-7944',6824679,'Do not know','Japan Post Holdings');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (96,'Cristian Wilson','dressguttural@gmail.com','(328)550-3825',2901145,'Do not know','Fannie Mae');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (97,'Jairo Rivera','uterinevalue@gmail.com','(683)581-759',5173913,'Do not know','Chevron');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (98,'Aldo Ramirez','chondrulevanish@gmail.com','(444)869-3025',2580297,'Do not know','Honda');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (99,'Julio Hughes','glossbarriers@gmail.com','(319)928-1194',5706544,'Do not know','Exor');
Insert into PRMSADMIN.VISITOR (VISID,VISNAME,VISEMAIL,VISPHONE,BADGEID,VISPURPOSE,VISCOMPANY) values (100,'Justin Williams','accountanthaptic@gmail.com','(209)698-3432',4212024,'Do not know','Daimler');
