--------------------------------------------------------
--  DDL for Table VISITOR
--------------------------------------------------------

  CREATE TABLE "PRMSADMIN"."VISITOR" 
   (	"VISID" NUMBER(*,0), 
	"VISNAME" VARCHAR2(100 BYTE), 
	"VISEMAIL" VARCHAR2(255 BYTE), 
	"VISPHONE" VARCHAR2(15 BYTE), 
	"BADGEID" NUMBER(*,0), 
	"VISPURPOSE" VARCHAR2(155 BYTE), 
	"VISCOMPANY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRMSTABLESPACE" ;
